
---
server:
  port: 8006
  error:
#    include-binding-errors: always
    include-message: always

spring:
  application:
    name: department-service
  jpa:
    hibernate:
      ddl-auto: update

---

---

#Database Credentials
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/department-service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12211221}

---
eureka:
  client:
    register-with-eureka: true
    serviceUrl.defaultZone: http://localhost:8001/eureka/
